const ipoData = [
    {
        id: 1,
        name: "Citius Transnet Investment Trust",
        priceBand: "₹100 - ₹105",
        openDate: "2026-04-17",
        closeDate: "2026-04-21",
        issueSize: "₹500 Cr",
        gmp: "₹12 (11.43%)",
        status: "Upcoming",
        type: "Mainboard",
        listingDate: "2026-04-28",
        lotSize: 150,
        subscription: { qib: "0x", nii: "0x", retail: "0x", total: "0x" },
        retailQuota: { sharesReserved: 500000, sharesApplied: 0, multiplier: 0, probability: "100%" },
        about: "Citius Transnet Investment Trust is an infrastructure investment trust focused on transport assets.",
        objectives: ["Asset acquisition", "General corporate purposes"],
        strengths: ["Strong revenue model", "Experienced management"],
        risks: ["Regulatory risks", "Interest rate fluctuations"],
        allotmentStatus: "Expected on 2026-04-24",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.0, risk: "Medium", growth: 4.2 },
        timeline: [
            { event: "Announcement", date: "2026-03-25", status: "completed" },
            { event: "IPO Open", date: "2026-04-17", status: "pending" },
            { event: "IPO Close", date: "2026-04-21", status: "pending" },
            { event: "Allotment", date: "2026-04-24", status: "pending" },
            { event: "Listing", date: "2026-04-28", status: "pending" }
        ]
    },
    {
        id: 2,
        name: "Property Share Investment Trust",
        priceBand: "₹150 - ₹160",
        openDate: "2026-04-10",
        closeDate: "2026-04-16",
        issueSize: "₹750 Cr",
        gmp: "₹25 (15.63%)",
        status: "Upcoming",
        type: "Mainboard",
        listingDate: "2026-04-23",
        lotSize: 90,
        subscription: { qib: "0x", nii: "0x", retail: "0x", total: "0x" },
        retailQuota: { sharesReserved: 800000, sharesApplied: 0, multiplier: 0, probability: "100%" },
        about: "Property Share Investment Trust provides investors with institutional-grade commercial real estate opportunities.",
        objectives: ["Property acquisition", "Debt reduction"],
        strengths: ["High-quality assets", "Transparent reporting"],
        risks: ["Market volatility", "Occupancy risks"],
        allotmentStatus: "Expected on 2026-04-20",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.2, risk: "Medium", growth: 4.5 },
        timeline: [
            { event: "Announcement", date: "2026-03-28", status: "completed" },
            { event: "IPO Open", date: "2026-04-10", status: "pending" },
            { event: "IPO Close", date: "2026-04-16", status: "pending" },
            { event: "Allotment", date: "2026-04-20", status: "pending" },
            { event: "Listing", date: "2026-04-23", status: "pending" }
        ]
    },
    {
        id: 3,
        name: "Om Power Transmission",
        priceBand: "₹85 - ₹92",
        openDate: "2026-04-09",
        closeDate: "2026-04-13",
        issueSize: "₹300 Cr",
        gmp: "₹18 (19.57%)",
        status: "Open",
        type: "Mainboard",
        listingDate: "2026-04-20",
        lotSize: 160,
        subscription: { qib: "0.5x", nii: "1.2x", retail: "2.1x", total: "0.9x" },
        retailQuota: { sharesReserved: 1200000, sharesApplied: 2520000, multiplier: 2.1, probability: "47.6%" },
        about: "Om Power Transmission specializes in electrical infrastructure and power distribution projects.",
        objectives: ["Project funding", "Working capital"],
        strengths: ["Strong order book", "Technical expertise"],
        risks: ["Project delays", "Material cost increases"],
        allotmentStatus: "Expected on 2026-04-16",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 3.8, risk: "High", growth: 4.0 },
        timeline: [
            { event: "Announcement", date: "2026-03-20", status: "completed" },
            { event: "IPO Open", date: "2026-04-09", status: "current" },
            { event: "IPO Close", date: "2026-04-13", status: "pending" },
            { event: "Allotment", date: "2026-04-16", status: "pending" },
            { event: "Listing", date: "2026-04-20", status: "pending" }
        ]
    },
    {
        id: 4,
        name: "Sai Parenteral's",
        priceBand: "₹120 - ₹128",
        openDate: "2026-03-24",
        closeDate: "2026-03-27",
        issueSize: "₹150 Cr",
        gmp: "₹15 (11.72%)",
        status: "Closed",
        type: "Mainboard",
        listingDate: "2026-04-03",
        lotSize: 110,
        subscription: { qib: "5.2x", nii: "12.1x", retail: "25.4x", total: "14.8x" },
        retailQuota: { sharesReserved: 400000, sharesApplied: 10160000, multiplier: 25.4, probability: "3.9%" },
        about: "Sai Parenteral's is a pharmaceutical company focusing on sterile injectable products.",
        objectives: ["R&D expansion", "Debt repayment"],
        strengths: ["Niche product range", "Quality certifications"],
        risks: ["Stringent regulations", "Supply chain issues"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.1, risk: "Medium", growth: 4.3 },
        timeline: [
            { event: "Announcement", date: "2026-03-05", status: "completed" },
            { event: "IPO Open", date: "2026-03-24", status: "completed" },
            { event: "IPO Close", date: "2026-03-27", status: "completed" },
            { event: "Allotment", date: "2026-04-01", status: "completed" },
            { event: "Listing", date: "2026-04-03", status: "completed" }
        ]
    },
    {
        id: 5,
        name: "Powerica",
        priceBand: "₹350 - ₹375",
        openDate: "2026-03-24",
        closeDate: "2026-03-27",
        issueSize: "₹1100 Cr",
        gmp: "₹85 (22.67%)",
        status: "Closed",
        type: "Mainboard",
        listingDate: "2026-04-03",
        lotSize: 40,
        subscription: { qib: "15.4x", nii: "35.2x", retail: "18.1x", total: "22.5x" },
        retailQuota: { sharesReserved: 1500000, sharesApplied: 27150000, multiplier: 18.1, probability: "5.5%" },
        about: "Powerica is a major player in the power generation equipment and services industry.",
        objectives: ["Capacity expansion", "Working capital"],
        strengths: ["Market leader", "Strong service network"],
        risks: ["Competition", "Economic slowdown"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.4, risk: "Low", growth: 4.6 },
        timeline: [
            { event: "Announcement", date: "2026-03-01", status: "completed" },
            { event: "IPO Open", date: "2026-03-24", status: "completed" },
            { event: "IPO Close", date: "2026-03-27", status: "completed" },
            { event: "Allotment", date: "2026-04-01", status: "completed" },
            { event: "Listing", date: "2026-04-03", status: "completed" }
        ]
    },
    {
        id: 6,
        name: "Amir Chand Jagdish Kumar (Exports)",
        priceBand: "₹210 - ₹225",
        openDate: "2026-03-24",
        closeDate: "2026-03-27",
        issueSize: "₹450 Cr",
        gmp: "₹40 (17.78%)",
        status: "Closed",
        type: "Mainboard",
        listingDate: "2026-04-03",
        lotSize: 65,
        subscription: { qib: "8.1x", nii: "15.4x", retail: "12.2x", total: "11.5x" },
        retailQuota: { sharesReserved: 600000, sharesApplied: 7320000, multiplier: 12.2, probability: "8.2%" },
        about: "Amir Chand Jagdish Kumar is a leading exporter of basmati rice and premium food products.",
        objectives: ["Export infrastructure", "Brand building"],
        strengths: ["Strong global footprint", "Quality products"],
        risks: ["Trade policy changes", "Commodity price risk"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.3, risk: "Medium", growth: 4.4 },
        timeline: [
            { event: "Announcement", date: "2026-03-02", status: "completed" },
            { event: "IPO Open", date: "2026-03-24", status: "completed" },
            { event: "IPO Close", date: "2026-03-27", status: "completed" },
            { event: "Allotment", date: "2026-04-01", status: "completed" },
            { event: "Listing", date: "2026-04-03", status: "completed" }
        ]
    },
    {
        id: 7,
        name: "Central Mine Planning & Design Institute",
        priceBand: "₹420 - ₹445",
        openDate: "2026-03-20",
        closeDate: "2026-03-24",
        issueSize: "₹1800 Cr",
        gmp: "₹65 (14.61%)",
        status: "Listed",
        type: "Mainboard",
        listingDate: "2026-04-01",
        lotSize: 33,
        subscription: { qib: "25.4x", nii: "45.1x", retail: "15.2x", total: "28.4x" },
        retailQuota: { sharesReserved: 2000000, sharesApplied: 30400000, multiplier: 15.2, probability: "6.6%" },
        about: "CMPDI is a premier consultant in the field of mineral exploration and mining engineering.",
        objectives: ["Investment in technology", "General corporate"],
        strengths: ["Government backing", "Unmatched expertise"],
        risks: ["Environmental regulations", "Policy shifts"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.6, risk: "Low", growth: 4.7 },
        timeline: [
            { event: "Announcement", date: "2026-02-25", status: "completed" },
            { event: "IPO Open", date: "2026-03-20", status: "completed" },
            { event: "IPO Close", date: "2026-03-24", status: "completed" },
            { event: "Allotment", date: "2026-03-27", status: "completed" },
            { event: "Listing", date: "2026-04-01", status: "completed" }
        ]
    },
    {
        id: 8,
        name: "GSP Crop Science",
        priceBand: "₹180 - ₹192",
        openDate: "2026-03-16",
        closeDate: "2026-03-18",
        issueSize: "₹250 Cr",
        gmp: "₹35 (18.23%)",
        status: "Listed",
        type: "Mainboard",
        listingDate: "2026-03-26",
        lotSize: 78,
        subscription: { qib: "12.1x", nii: "25.4x", retail: "45.2x", total: "28.5x" },
        retailQuota: { sharesReserved: 400000, sharesApplied: 18080000, multiplier: 45.2, probability: "2.2%" },
        about: "GSP Crop Science is a leading manufacturer of agrochemicals and pesticides.",
        objectives: ["New manufacturing unit", "Working capital"],
        strengths: ["Strong R&D", "Wide distribution network"],
        risks: ["Monsoon dependency", "Raw material costs"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.2, risk: "Medium", growth: 4.4 },
        timeline: [
            { event: "Announcement", date: "2026-02-20", status: "completed" },
            { event: "IPO Open", date: "2026-03-16", status: "completed" },
            { event: "IPO Close", date: "2026-03-18", status: "completed" },
            { event: "Allotment", date: "2026-03-21", status: "completed" },
            { event: "Listing", date: "2026-03-26", status: "completed" }
        ]
    },
    {
        id: 9,
        name: "Raajmarg Infra Investment Trust",
        priceBand: "₹100 - ₹105",
        openDate: "2026-03-11",
        closeDate: "2026-03-13",
        issueSize: "₹1500 Cr",
        gmp: "₹10 (9.52%)",
        status: "Listed",
        type: "Mainboard",
        listingDate: "2026-03-23",
        lotSize: 140,
        subscription: { qib: "5.1x", nii: "8.4x", retail: "12.1x", total: "8.2x" },
        retailQuota: { sharesReserved: 2500000, sharesApplied: 30250000, multiplier: 12.1, probability: "8.3%" },
        about: "Raajmarg Infra InvIT manages road infrastructure assets across India.",
        objectives: ["Debt reduction", "New asset acquisition"],
        strengths: ["Predictable cash flows", "Strategic road assets"],
        risks: ["Regulatory changes", "Traffic volume risk"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.1, risk: "Low", growth: 4.3 },
        timeline: [
            { event: "Announcement", date: "2026-02-15", status: "completed" },
            { event: "IPO Open", date: "2026-03-11", status: "completed" },
            { event: "IPO Close", date: "2026-03-13", status: "completed" },
            { event: "Allotment", date: "2026-03-18", status: "completed" },
            { event: "Listing", date: "2026-03-23", status: "completed" }
        ]
    },
    {
        id: 10,
        name: "Innovision",
        priceBand: "₹280 - ₹305",
        openDate: "2026-03-10",
        closeDate: "2026-03-17",
        issueSize: "₹600 Cr",
        gmp: "₹45 (14.75%)",
        status: "Listed",
        type: "Mainboard",
        listingDate: "2026-03-25",
        lotSize: 48,
        subscription: { qib: "12.1x", nii: "25.4x", retail: "45.2x", total: "28.5x" },
        retailQuota: { sharesReserved: 800000, sharesApplied: 36160000, multiplier: 45.2, probability: "2.2%" },
        about: "Innovision is a technology-driven security and facility management services provider.",
        objectives: ["Tech upgrade", "Brand building"],
        strengths: ["Strong client base", "Scalable model"],
        risks: ["Labor regulations", "Competitive pricing"],
        allotmentStatus: "Allotment Finalized",
        lastUpdated: "2026-04-09 03:45 PM",
        ratings: { fundamental: 4.2, risk: "Medium", growth: 4.6 },
        timeline: [
            { event: "Announcement", date: "2026-02-10", status: "completed" },
            { event: "IPO Open", date: "2026-03-10", status: "completed" },
            { event: "IPO Close", date: "2026-03-17", status: "completed" },
            { event: "Allotment", date: "2026-03-20", status: "completed" },
            { event: "Listing", date: "2026-03-25", status: "completed" }
        ]
    }
];

const newsData = [
    {
        id: 1775729900,
        title: "Live Market Sync: April 09, 2026",
        date: "2026-04-09",
        summary: "Market dashboard updated with real IPO data from Chittorgarh reference. Om Power Transmission is now LIVE."
    },
    {
        id: 1,
        title: "Market Outlook 2026: What investors should expect?",
        date: "2026-03-07",
        summary: "Experts predict a bullish market for the first half of 2026, driven by infrastructure growth."
    },
    {
        id: 2,
        title: "FinTech Innovations IPO Subscribed 11.8x on final day.",
        date: "2026-03-07",
        summary: "The IPO saw strong interest from retail and QIB investors alike."
    }
];
